version: 0.2
phases:
  install:
    commands:
      - nodejs: 16
        sudo yum install nodejs -y
  pre_build:
    commands:
      - npm install
  build:
   commands:
     - npm build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://$BUCKET_NAME/
      - aws cloudfront create-invalidation — distribution-id $DIST_ID — paths '/*'
artifacts:
  files:
   - '**/*'
  base-directory: build
