version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install yarn
      - yarn
      - yarn add eslint-config-react-app
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://$BUCKET_NAME/
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
artifacts:
  files:
    - '**/*'
  base-directory: build
